# Hexo site configuration
title: My Blog
subtitle: 'Powered by Hexo + Volantis'
description: '一个运行在低配服务器上的静态博客'
keywords: [blog, hexo, volantis]
author: admin
language: zh-CN
timezone: Asia/Shanghai

url: http://hubery.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

index_generator:
  path: ''
  per_page: 10
  order_by: -date

category_generator:
  per_page: 10
archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
tag_generator:
  per_page: 10

theme: volantis

deploy:
  type: ''
